var Patient = {
  info: {
    gender: false,
    age: false,
    phone: false,
    date: false,
    number: false,
    nomobile: false,
    covidAlert: false,
    geolocation: {
      lat: false,
      lng: false,
    },
  },
  ruleOut: {
    intensiveCareInLastMonth: true,
    cancer: true,
    immuneDefficiency: true,
    chemoInLast2Months: true,
    dyspnea: true,
    acuteMotorImpairment: true,
    chestPain: true,
    hematemesis: true,
  },
  symptoms: {
    fever: {
      isPresent: false,
      measured: false,
      durationInDays: null,
      abortedWithAntipyretics: false,
    },
    cough: {
      isPresent: false,
      sputum: {
        isPresent: false,
        color: {
          isGreen: false,
          isYellow: false,
          isTransparent: false,
          isWhite: false,
          isRed: false,
        },
      },
    },
    abdominalPain: {
      isPresent: false,
      durationInDays: null,
      location: {
        one: false,
        two: false,
        three: false,
        four: false,
        five: false,
        six: false,
        seven: false,
        eight: false,
        nine: false,
      },
    },
    throatPain: {
      isPresent: false,
      voiceChange: false,
      durationInDays: null,
    },
    runnyNose: {
      isPresent: false,
      sputum: {
        color: {
          isGreen: false,
          isYellow: false,
          isTransparent: false,
          isWhite: false,
          isRed: false,
        },
      },
    },
    urinatingPain: {
      isPresent: false,
      durationInDays: null,
      secretions: {
        isPresent: false,
        color: {
          isGreen: false,
          isYellow: false,
          isTransparent: false,
          isWhite: false,
          isRed: false,
        },
      },
    },
    diarrhea: {
      isPresent: false,
      color: {
        isRed: false,
        isBlack: false,
      },
    },
    vomiting: {
      isPresent: false,
    },
    pain: {
      isPresent: false,
      location: {
        rightLeg: false,
        leftLeg: false,
        rightArm: false,
        leftArm: false,
        head: false,
        neck: false,
        lumbar: false,
      },
    },
    edema: {
      isPresent: false,
      location: {
        rightLeg: false,
        leftLeg: false,
        face: false,
      },
    },
    headache: {
      isPresent: false,
      characteristics: {
        intensity: false,
        pulsating: false,
        wholeHead: false,
        neckPain: false,
      },
    },
  },
  lab: {
    isPresent: false,
    values: {
      hemograma: {
        hto: false,
        hb: false,
        gb: {
          count: false,
          neu: false,
          lin: false,
          mon: false,
          eos: false,
          bas: false,
        },
        plqt: false,
        ferritina: false,
        transferrina: false,
        satTransferrina: false,
        TIBC: false,
        ferremia: false,
        vcm: false,
        rdw: false,
        vsg: false,
        pcr: false,
        acidofolico: false,
        b12: false,
        LDH: false,
      },
      renal: {
        urea: false,
        creatinina: false,
      },
      ionograma: {
        na: false,
        k: false,
        cl: false,
        p: false,
        mg: false,
      },
      eab: {
        ph: false,
        po2: false,
        pco2: false,
        hco3: false,
        eb: false,
        sato2: false,
      },
      hepatograma: {
        bt: false,
        bd: false,
        bi: false,
        fal: false,
        tgo: false,
        tgp: false,
        amilasa: false,
        lipasa: false,
        gammagt: false,
        nucleot5: false,
        albumina: false,
        proteinas: false,
      },
      coagulograma: {
        tp: false,
        kptt: false,
        RIN: false,
        factores: {
          XVIII: false,
          V: false,
        },
      },
    },
  },
};

module.exports = Patient;
